nodeLinker: node-modules

# Publish @public-information-symbols/* packages to the public npm registry.
npmScopes:
  public-information-symbols:
    npmRegistryServer: 'https://registry.npmjs.org/'
    npmAuthToken: '${NPM_JS_AUTH:-}'
